apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: importcenter
  template:
    metadata:
      labels:
        app: importcenter
        project: service
    spec:
      terminationGracePeriodSeconds: 0
      securityContext:
        runAsUser: 1001180000
        runAsGroup: 1001180000
        fsGroup: 1001180000
      containers:
      - name: api
        image: remote-docker.artifactory.dbgcloud.io/okteto/hello-world:java-maven
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: "2"
            memory: 3Gi

---

apiVersion: v1
kind: Service
metadata:
  name: hello-world
  annotations:
    dev.okteto.com/auto-ingress: "true"
  labels:
    app: importcenter
spec:
  type: ClusterIP
  ports:
    - name: hello-world
      port: 8080
  selector:
    app: importcenter
